#### GENERAL IDEAS

# SCR PROBABILITY, GIVEN THIS IS A RUN PLAY. ON THE OTHER HAND ... DEFINITELY WOULD BE SKEWED BY CERTAIN QBS / SYSTEMS. LET'S PUSH IT FOR NEXT YEAR GIVEN POTENTIAL FOR SCREWY SHIT BUT ALSO MORE LIKELY ON CERTAIN DOWNS / DISTANCEX
# ADOT PREDICTION? WOULD BE INTERESTING. NOT AS MUCH RIGGING / SLANTED TOWARDS CERTAIN QBS ALMOST CERTAINLY. 
# IN PRESSURE --> CREATE A PRESSURE RATE STAT FOR NON-QB PRESSURES. TO DO FOR SURE.
# INT PROBABILITY --> DEFINITELY SOMETHING TO DO. TO DO FOR SURE..
# TIME OF POSSESSION?
# DID YOU GET MORE PLAYS / POSSESSION THAN THE OTHER SIDE?
# SPECIAL TEAMS -  STARTING FIELD POSITION BY TEAM WITH NEW KICKOFF