SELECT
  team_name,
week,
season,
SUM(pa_passing_snaps) AS pa_snaps,
SUM(npa_passing_snaps) AS npa_snaps,
(CAST(SUM(pa_passing_snaps) AS DOUBLE) / NULLIF((SUM(pa_passing_snaps) + SUM(npa_passing_snaps)), 0)) AS pa_rate,
(CAST(SUM(pa_def_gen_pressures) AS DOUBLE) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_pressure_rate,
(CAST(SUM(npa_def_gen_pressures) AS DOUBLE) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_pressure_rate,
(SUM((pa_passing_snaps * pa_grades_pass)) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_grade,
(SUM((npa_passing_snaps * npa_grades_pass)) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_grade,
(SUM((pa_passing_snaps * pa_avg_time_to_throw)) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_time_to_throw,
(SUM((npa_passing_snaps * npa_avg_time_to_throw)) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_time_to_throw,
(SUM((pa_passing_snaps * pa_ypa)) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_ypa,
(SUM((npa_passing_snaps * npa_ypa)) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_ypa,
(SUM((pa_passing_snaps * pa_accuracy_percent)) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_acc_pct,
(SUM((npa_passing_snaps * npa_accuracy_percent)) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_acc_pct,
(SUM((pa_passing_snaps * pa_qb_rating)) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_qbr,
(SUM((npa_passing_snaps * npa_qb_rating)) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_qbr,
(SUM((pa_passing_snaps * pa_btt_rate)) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_btt_rate,
(SUM((npa_passing_snaps * npa_btt_rate)) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_btt_rate,
(SUM((pa_passing_snaps * pa_twp_rate)) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_twp_rate,
(SUM((npa_passing_snaps * npa_twp_rate)) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_twp_rate,
(SUM((pa_passing_snaps * pa_avg_depth_of_target)) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_adot,
(SUM((npa_passing_snaps * npa_avg_depth_of_target)) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_adot,
(CAST(SUM(pa_scrambles) AS DOUBLE) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_scr_rate,
(CAST(SUM(npa_scrambles) AS DOUBLE) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_scr_rate,
(CAST(SUM(pa_sacks) AS DOUBLE) / NULLIF(SUM(pa_passing_snaps), 0)) AS pa_sack_pct,
(CAST(SUM(npa_sacks) AS DOUBLE) / NULLIF(SUM(npa_passing_snaps), 0)) AS npa_sack_pct,
((SUM((pa_passing_snaps * pa_grades_pass)) / NULLIF(SUM(pa_passing_snaps), 0)) - (SUM((npa_passing_snaps * npa_grades_pass)) / NULLIF(SUM(npa_passing_snaps), 0))) AS grade_difference,
((SUM((pa_passing_snaps * pa_avg_time_to_throw)) / NULLIF(SUM(pa_passing_snaps), 0)) - (SUM((npa_passing_snaps * npa_avg_time_to_throw)) / NULLIF(SUM(npa_passing_snaps), 0))) AS ttt_difference,
((SUM((pa_passing_snaps * pa_ypa)) / NULLIF(SUM(pa_passing_snaps), 0)) - (SUM((npa_passing_snaps * npa_ypa)) / NULLIF(SUM(npa_passing_snaps), 0))) AS ypa_difference,
((SUM((pa_passing_snaps * pa_accuracy_percent)) / NULLIF(SUM(pa_passing_snaps), 0)) - (SUM((npa_passing_snaps * npa_accuracy_percent)) / NULLIF(SUM(npa_passing_snaps), 0))) AS acc_pct_difference,
((SUM((pa_passing_snaps * pa_qb_rating)) / NULLIF(SUM(pa_passing_snaps), 0)) - (SUM((npa_passing_snaps * npa_qb_rating)) / NULLIF(SUM(npa_passing_snaps), 0))) AS qbr_difference,
((SUM((pa_passing_snaps * pa_btt_rate)) / NULLIF(SUM(pa_passing_snaps), 0)) - (SUM((npa_passing_snaps * npa_btt_rate)) / NULLIF(SUM(npa_passing_snaps), 0))) AS btt_difference,
((SUM((pa_passing_snaps * pa_twp_rate)) / NULLIF(SUM(pa_passing_snaps), 0)) - (SUM((npa_passing_snaps * npa_twp_rate)) / NULLIF(SUM(npa_passing_snaps), 0))) AS twp_difference,
((SUM((pa_passing_snaps * pa_avg_depth_of_target)) / NULLIF(SUM(pa_passing_snaps), 0)) - (SUM((npa_passing_snaps * npa_avg_depth_of_target)) / NULLIF(SUM(npa_passing_snaps), 0))) AS adot_difference,
((CAST(SUM(pa_scrambles) AS DOUBLE) / NULLIF(SUM(pa_passing_snaps), 0)) - (CAST(SUM(npa_scrambles) AS DOUBLE) / NULLIF(SUM(npa_passing_snaps), 0))) AS scr_rate_difference,
((CAST(SUM(pa_def_gen_pressures) AS DOUBLE) / NULLIF(SUM(pa_passing_snaps), 0)) - (CAST(SUM(npa_def_gen_pressures) AS DOUBLE) / NULLIF(SUM(npa_passing_snaps), 0))) AS pressure_rate_difference,
((CAST(SUM(pa_sacks) AS DOUBLE) / NULLIF(SUM(pa_passing_snaps), 0)) - (CAST(SUM(npa_sacks) AS DOUBLE) / NULLIF(SUM(npa_passing_snaps), 0))) AS sack_rate_difference
FROM
  {{ ref('stg_pff__passing_concept') }}
GROUP BY team_name, week, season
