SELECT
  team_name,
week,
season,
SUM(less_passing_snaps) AS less_snaps,
SUM(more_passing_snaps) AS more_snaps,
(CAST(SUM(less_passing_snaps) AS DOUBLE) / (SUM(less_passing_snaps) + SUM(more_passing_snaps))) AS less_rate,
(CAST(SUM(less_def_gen_pressures) AS DOUBLE) / NULLIF(SUM(less_passing_snaps), 0)) AS less_pressure_rate,
(CAST(SUM(more_def_gen_pressures) AS DOUBLE) / NULLIF(SUM(more_passing_snaps), 0)) AS more_pressure_rate,
(SUM((less_passing_snaps * less_grades_pass)) / NULLIF(SUM(less_passing_snaps), 0)) AS less_grade,
(SUM((more_passing_snaps * more_grades_pass)) / NULLIF(SUM(more_passing_snaps), 0)) AS more_grade,
(SUM((less_passing_snaps * less_avg_time_to_throw)) / NULLIF(SUM(less_passing_snaps), 0)) AS less_time_to_throw,
(SUM((more_passing_snaps * more_avg_time_to_throw)) / NULLIF(SUM(more_passing_snaps), 0)) AS more_time_to_throw,
(SUM((less_passing_snaps * less_ypa)) / NULLIF(SUM(less_passing_snaps), 0)) AS less_ypa,
(SUM((more_passing_snaps * more_ypa)) / NULLIF(SUM(more_passing_snaps), 0)) AS more_ypa,
(SUM((less_passing_snaps * less_accuracy_percent)) / NULLIF(SUM(less_passing_snaps), 0)) AS less_acc_pct,
(SUM((more_passing_snaps * more_accuracy_percent)) / NULLIF(SUM(more_passing_snaps), 0)) AS more_acc_pct,
(SUM((less_passing_snaps * less_qb_rating)) / NULLIF(SUM(less_passing_snaps), 0)) AS less_qbr,
(SUM((more_passing_snaps * more_qb_rating)) / NULLIF(SUM(more_passing_snaps), 0)) AS more_qbr,
(SUM((less_passing_snaps * less_btt_rate)) / NULLIF(SUM(less_passing_snaps), 0)) AS less_btt_rate,
(SUM((more_passing_snaps * more_btt_rate)) / NULLIF(SUM(more_passing_snaps), 0)) AS more_btt_rate,
(SUM((less_passing_snaps * less_twp_rate)) / NULLIF(SUM(less_passing_snaps), 0)) AS less_twp_rate,
(SUM((more_passing_snaps * more_twp_rate)) / NULLIF(SUM(more_passing_snaps), 0)) AS more_twp_rate,
ROUND((CAST(SUM(less_interceptions) AS DOUBLE) / NULLIF(SUM(less_passing_snaps), 0)), 10) AS less_int_rate,
ROUND((CAST(SUM(more_interceptions) AS DOUBLE) / NULLIF(SUM(more_passing_snaps), 0)), 10) AS more_int_rate,
(SUM((less_passing_snaps * less_avg_depth_of_target)) / NULLIF(SUM(less_passing_snaps), 0)) AS less_adot,
(SUM((more_passing_snaps * more_avg_depth_of_target)) / NULLIF(SUM(more_passing_snaps), 0)) AS more_adot,
(CAST(SUM(less_scrambles) AS DOUBLE) / NULLIF(SUM(less_passing_snaps), 0)) AS less_scr_rate,
(CAST(SUM(more_scrambles) AS DOUBLE) / NULLIF(SUM(more_passing_snaps), 0)) AS more_scr_rate,
(CAST(SUM(less_sacks) AS DOUBLE) / NULLIF(SUM(less_passing_snaps), 0)) AS less_sack_pct,
(CAST(SUM(more_sacks) AS DOUBLE) / NULLIF(SUM(more_passing_snaps), 0)) AS more_sack_pct,
((SUM((less_passing_snaps * less_grades_pass)) / NULLIF(SUM(less_passing_snaps), 0)) - (SUM((more_passing_snaps * more_grades_pass)) / NULLIF(SUM(more_passing_snaps), 0))) AS grade_difference,
((SUM((less_passing_snaps * less_avg_time_to_throw)) / NULLIF(SUM(less_passing_snaps), 0)) - (SUM((more_passing_snaps * more_avg_time_to_throw)) / NULLIF(SUM(more_passing_snaps), 0))) AS ttt_difference,
((SUM((less_passing_snaps * less_ypa)) / NULLIF(SUM(less_passing_snaps), 0)) - (SUM((more_passing_snaps * more_ypa)) / NULLIF(SUM(more_passing_snaps), 0))) AS ypa_difference,
((SUM((less_passing_snaps * less_accuracy_percent)) / NULLIF(SUM(less_passing_snaps), 0)) - (SUM((more_passing_snaps * more_accuracy_percent)) / NULLIF(SUM(more_passing_snaps), 0))) AS acc_pct_difference,
((SUM((less_passing_snaps * less_qb_rating)) / NULLIF(SUM(less_passing_snaps), 0)) - (SUM((more_passing_snaps * more_qb_rating)) / NULLIF(SUM(more_passing_snaps), 0))) AS qbr_difference,
((SUM((less_passing_snaps * less_btt_rate)) / NULLIF(SUM(less_passing_snaps), 0)) - (SUM((more_passing_snaps * more_btt_rate)) / NULLIF(SUM(more_passing_snaps), 0))) AS btt_difference,
((SUM((less_passing_snaps * less_twp_rate)) / NULLIF(SUM(less_passing_snaps), 0)) - (SUM((more_passing_snaps * more_twp_rate)) / NULLIF(SUM(more_passing_snaps), 0))) AS twp_difference,
((SUM((less_passing_snaps * less_avg_depth_of_target)) / NULLIF(SUM(less_passing_snaps), 0)) - (SUM((more_passing_snaps * more_avg_depth_of_target)) / NULLIF(SUM(more_passing_snaps), 0))) AS adot_difference,
((CAST(SUM(less_scrambles) AS DOUBLE) / NULLIF(SUM(less_passing_snaps), 0)) - (CAST(SUM(more_scrambles) AS DOUBLE) / NULLIF(SUM(more_passing_snaps), 0))) AS scr_rate_difference,
((CAST(SUM(less_def_gen_pressures) AS DOUBLE) / NULLIF(SUM(less_passing_snaps), 0)) - (CAST(SUM(more_def_gen_pressures) AS DOUBLE) / NULLIF(SUM(more_passing_snaps), 0))) AS pressure_rate_difference,
((CAST(SUM(less_sacks) AS DOUBLE) / NULLIF(SUM(less_passing_snaps), 0)) - (CAST(SUM(more_sacks) AS DOUBLE) / NULLIF(SUM(more_passing_snaps), 0))) AS sack_rate_difference
FROM
  {{ ref('stg_pff__passing_tip') }}
GROUP BY team_name, week, season
